#!/bin/bash

#echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER-nopassword

FILE=/etc/sudoers.d/$USER-nopassword
echo $FILE

if [ ! -f "$FILE" ]; then
    echo "creo sudoers no password "
    echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER-nopassword
fi

cat $FILE
