#!/bin/bash

#echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER-nopassword

FILE=/etc/sudoers.d/$USER-nopassword
#echo $FILE

if [ ! -f "$FILE" ]; then
    echo "*********************************"
    echo "* creo sudoers no password      *"
    echo "*********************************"
    echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER-nopassword
else 
    echo "*********************************"
    echo "* sudoers no password esistente *"
    echo "*********************************"

fi

#cat $FILE
